export * from './header/header.component'
export * from './footer/footer.component'
export * from './actors/actors.component'
export * from './films/films.component'
export * from './home/home.component'